### PR TITLE
Make clippy happy

### PR DESCRIPTION
**Pull request by matthiasgoergens**
Specifically, the new nightly clippy.  To prepare for moving to latest nightly, soon.

### CODE REVIEW

**Comment by matthiasgoergens** [comment]
Ha, clippy fails, because they renamed they renamed a rule (I think):

```
 111 | #[allow(clippy::single_range_in_vec_init)]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: did you mean: `clippy::rc_clone_in_vec_init`
```

So we can't make both the current clippy and the new clippy happy.  At least not trivially.  Let me see how to fix this.  Or perhaps we just move to the new nightly.

**Comment by matthiasgoergens** [comment]
> I think this is getting superseded by #1156.

I think you might have mis-copy-pasted something?  #1156 is this PR.

**Comment by Nashtare** [comment]
Woops sorry, I meant https://github.com/mir-protocol/plonky2/pull/1220

**Comment by matthiasgoergens** [comment]
Closed in favour of https://github.com/mir-protocol/plonky2/pull/1220

**Pull request closed without merging**
