### PR TITLE
Implement inverse from Fermat little theorem

### PR DESCRIPTION
**Pull request by Nashtare**
Mostly copied from https://github.com/Plonky3/Plonky3/pull/40, which itself is based on winterfell implementation. Sharing my results below (though they were already assessed on plonky3 related PR). I'm on  i7-9750H CPU @ 2.60GHz with Ubuntu 22.04.

image

### CODE REVIEW

**Comment by unzvfu** [comment]
Hmm, strangely I'm only seeing

> time:   [153.13 ns 153.61 ns 154.12 ns]

compared to ~140 ns in Plonky3. Are you seeing the same benchmark numbers for both?

(Also, please don't `force-push` to public branches such as PRs, it can create conflicts when someone who has checked it out tries to update.)

**Comment by Nashtare** [comment]
> (Also, please don't force-push to public branches such as PRs, it can create conflicts when someone who has checked it out tries to update.)

My apologies, I was fixing a typo in the description.

> Hmm, strangely I'm only seeing
> > time: [153.13 ns 153.61 ns 154.12 ns]
> 
> compared to ~140 ns in Plonky3. Are you seeing the same benchmark numbers for both?

I'm indeed getting a slower benchmark compared to the Plonky3 version. I noticed that changing the inlining from `#[inline(always)]` to `#[inline]` seemed to improve slightly improve the base case, but significantly worsen the extension fields inverse benchmarks. Is the field implementation in Plonky3 strictly identical? I'm not too familiar with it yet. 

The numbers you shared seem identical to the ones shared in https://github.com/Plonky3/Plonky3/pull/40, do you not see any changes at all? If so I'd be quite surprised, as my results above are from a comparison with the inverse currently in main, and I am definitely getting a noticeable performance improvement.

**Comment by Nashtare** [comment]
What's your error? And which version of nightly are you using? I'm on nightly-2023-07-01 and have no issues.

**Comment by 0xKanekiKen** [comment]
```
Compiling plonky2_evm v0.1.1 (/home/admin/plonky2/evm)
error[E0493]: destructor of `[std::ops::RangeInclusive<u8>; N]` cannot be evaluated at compile-time
  --> evm/src/cpu/kernel/constants/exc_bitfields.rs:7:53
   |
7  | const fn u256_from_set_index_ranges<const N: usize>(ranges: [RangeInclusive<u8>; N]) -> U256 {
   |                                                     ^^^^^^ the destructor for this type cannot be evaluated in constant functions
...
29 | }
   | - value is dropped here

For more information about this error, try `rustc --explain E0493`.
error: could not compile `plonky2_evm` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `plonky2_evm` (lib test) due to previous error
```

I have `1.73.0-nightly (d78bbf4bd 2023-08-03)`. Let me downgrade and try to build it again.

**Review by 0xKanekiKen — COMMENTED** [review]
If I comment out `#[inline(always)]` here, then, I'm seeing almost the same performance as in `plonky3`

**Comment by 0xKanekiKen** [comment]
This is what I was seeing yesterday:

```
Bench of your PR with #[inline(always]

Running benches/ffts.rs (target/release/deps/ffts-429ef95e0cc33801)                                              
Gnuplot not found, using plotters backend                                                                             
     Running benches/field_arithmetic.rs (target/release/deps/field_arithmetic-0703e6e5ab7fc128)                      
Gnuplot not found, using plotters backend                                                                             
try_inverse<GoldilocksField>                                                                                          
                        time:   [146.83 ns 147.16 ns 147.64 ns]                                                       
Found 7 outliers among 100 measurements (7.00%)                                                                       
  3 (3.00%) high mild                                                                                                 
  4 (4.00%) high severe                                                                                               
                                                                                                                      
Benchmarking try_inverse<QuadraticExtension<GoldilocksField>>: Collecting 100 samples in estimated 5.0010 s (8.8M iter
try_inverse<QuadraticExtension<GoldilocksField>>                                                                      
                        time:   [162.72 ns 162.95 ns 163.20 ns]                                                       
Found 7 outliers among 100 measurements (7.00%)                                                                       
  3 (3.00%) high mild                                                                                                 
  4 (4.00%) high severe                                                                                               
                                                                                                                      
Benchmarking try_inverse<QuarticExtension<GoldilocksField>>: Collecting 100 samples in estimated 5.0054 s (4.6M iterat
try_inverse<QuarticExtension<GoldilocksField>>                                                                        
                        time:   [236.98 ns 237.18 ns 237.40 ns]                                                       
Found 11 outliers among 100 measurements (11.00%)                                                                     
  6 (6.00%) high mild                                                                                                 
  5 (5.00%) high severe                                                                                               
                                                                                                                      
Benchmarking try_inverse<QuinticExtension<GoldilocksField>>: Collecting 100 samples in estimated 5.0054 s (4.0M iterat
try_inverse<QuinticExtension<GoldilocksField>>                                                                        
                        time:   [241.14 ns 241.44 ns 241.78 ns]                                                       
Found 12 outliers among 100 measurements (12.00%)                                                                     
  3 (3.00%) high mild                                                                                                 
  9 (9.00%) high severe
  ```
  
  *main*
  
  ```
  Running benches/ffts.rs (target/release/deps/ffts-429ef95e0cc33801)                                              
Gnuplot not found, using plotters backend                                                                             
     Running benches/field_arithmetic.rs (target/release/deps/field_arithmetic-0703e6e5ab7fc128)                      
Gnuplot not found, using plotters backend                                                                             
try_inverse<GoldilocksField>                                                                                          
                        time:   [157.99 ns 158.11 ns 158.27 ns]                                                       
                        change: [+7.5767% +8.0559% +8.5456%] (p = 0.00 < 0.05)                                        
                        Performance has regressed.                                                                    
Found 11 outliers among 100 measurements (11.00%)                                                                     
  5 (5.00%) high mild                                                                                                 
  6 (6.00%) high severe                                                                                               
                                                                                                                      
Benchmarking try_inverse<QuadraticExtension<GoldilocksField>>: Collecting 100 samples in estimated 5.0027 s (8.8M iter
try_inverse<QuadraticExtension<GoldilocksField>>                                                                      
                        time:   [172.34 ns 172.55 ns 172.84 ns]                                                       
                        change: [+5.4235% +6.0818% +6.7582%] (p = 0.00 < 0.05)                                        
                        Performance has regressed.                                                                    
Found 10 outliers among 100 measurements (10.00%)                                                                     
  4 (4.00%) high mild                                                                                                 
  6 (6.00%) high severe                                                                                               
                                                                                                                      
Benchmarking try_inverse<QuarticExtension<GoldilocksField>>: Collecting 100 samples in estimated 5.0005 s (4.8M iterat
try_inverse<QuarticExtension<GoldilocksField>>                                                                        
                        time:   [238.78 ns 239.06 ns 239.42 ns]                                                       
                        change: [+0.3805% +0.9980% +1.6248%] (p = 0.00 < 0.05)                                        
                        Change within noise threshold.                                                                
Found 8 outliers among 100 measurements (8.00%)                                                                       
  1 (1.00%) high mild                                                                                                 
  7 (7.00%) high severe                                                                                               
                                                                                                                      
Benchmarking try_inverse<QuinticExtension<GoldilocksField>>: Collecting 100 samples in estimated 5.0054 s (3.9M iterat
try_inverse<QuinticExtension<GoldilocksField>>                                                                        
                        time:   [249.88 ns 250.11 ns 250.38 ns]                                                       
                        change: [+3.1823% +3.8824% +4.6071%] (p = 0.00 < 0.05)                                        
                        Performance has regressed.                                                                    
Found 10 outliers among 100 measurements (10.00%)                                                                     
  3 (3.00%) high mild                                                                                                 
  7 (7.00%) high severe
  ```

**Comment by Nashtare** [comment]
Thanks for the additional comparison @0xKanekiKen. 
Seems you're getting a slight improvement as well for the other cases when inlining is removed, so perhaps the issue is coming from my config somehow.

**Comment by Nashtare** [comment]
@unzvfu Have you been able to confirm whether without the inlining attribute you could get back to the Plonky3 performances on your end?

**Comment by unzvfu** [comment]
> @unzvfu Have you been able to confirm whether without the inlining attribute you could get back to the Plonky3 performances on your end?

(Apologies for the delay.) I see a minor improvement when inlining is removed (less than 2%). I'm still seeing a ~10ns difference (~152ns vs ~142ns) between Plonky2 and Plonky3, even though the benchmarks and implementations are identical. Very strange.

Anyway, I think it's fine to go with this as is; keep us posted if the mystery is resolved.

**Review by unzvfu — APPROVED** [review]
Looks good; thanks!

**Pull request merged**
