### PR TITLE
`registers` -> `columns`

### PR DESCRIPTION
**Pull request by wborgeaud**
~~Rename some `columns` modules to `registers` for consistency.~~
Edit: Rename some `registers` modules to `columns` for consistency.

### CODE REVIEW

**Review by dlubarov — APPROVED** [review]
LGTM

**Comment by nbgl** [comment]
I am 100% for consistency but I do think “columns” is actually more descriptive. When you say “register”, I think of EVM registers (i.e., the stack and the program counter).

**Comment by wborgeaud** [comment]
> I am 100% for consistency but I do think “columns” is actually more descriptive. When you say “register”, I think of EVM registers (i.e., the stack and the program counter).

Yeah makes sense. I don't have a strong opinion on this so either works for me. I just think we need to be consistent across the crate.
Does anybody else have a preference on this?

**Comment by bpfarmer** [comment]
I actually like columns for what it's worth.

**Comment by unzvfu** [comment]
> > I am 100% for consistency but I do think “columns” is actually more descriptive. When you say “register”, I think of EVM registers (i.e., the stack and the program counter).
> 
> Yeah makes sense. I don't have a strong opinion on this so either works for me. I just think we need to be consistent across the crate. Does anybody else have a preference on this?

I don't have strong feelings either way, but I agree with @nbgl's point that we should try to clearly distinguish the concepts of EVM register and our columns/registers. Using "column" for our side seems like a good option.

**Comment by wborgeaud** [comment]
By popular demand I changed this to use "columns" instead of "registers".

**Pull request merged**
